In [1]:
import numpy as np
import pandas as pd

In [2]:
train = pd.read_csv('../data/titanic/train.csv')
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [4]:
label = ['Survived']
feature = ['Pclass','Sex', 'Age', 'Fare']

In [5]:
train[feature].head()

Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [6]:
train[label].head()

Survived
0         0
1         1
2         1
3         1
4         0

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_valid, y_train, y_valid = train_test_split\
(train[feature], train[label], test_size=0.2, random_state=30)

In [8]:
x_train.shape, x_valid.shape

((712, 4), (179, 4))

### 결측치

In [10]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [4]:
# 결측이면 true, 아니면 false
# true:1, false:0
# sum -> true의 갯수(결측치 수)
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [13]:
train['Age'].isnull().sum()

177

In [14]:
train['Age'].describescribe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [15]:
train['Age'].fillna(0).describe()

count    891.000000
mean      23.799293
std       17.596074
min        0.000000
25%        6.000000
50%       24.000000
75%       35.000000
max       80.000000
Name: Age, dtype: float64

In [17]:
# 나이평균으로 결측치 채움
train['Age'].fillna(train['Age'].mean()).describe()

count    891.000000
mean      29.699118
std       13.002015
min        0.420000
25%       22.000000
50%       29.699118
75%       35.000000
max       80.000000
Name: Age, dtype: float64

In [5]:
# 사이킷런에서 결측치 처리해주는 라이브러리
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')

In [6]:
# 학습
imputer.fit(train[['Age','Pclass']])

SimpleImputer()

In [7]:
# 변형
result = imputer.transform(train[['Age', 'Pclass']])

In [8]:
train[['Age','Pclass']] = result # 기존 데이터프레임에 대입

In [9]:
train[['Age','Pclass']].isnull().sum()

Age       0
Pclass    0
dtype: int64

In [27]:
train['Age'].describe()

count    891.000000
mean      29.699118
std       13.002015
min        0.420000
25%       22.000000
50%       29.699118
75%       35.000000
max       80.000000
Name: Age, dtype: float64

In [12]:
# fit, transform 한방에
train=pd.read_csv('../data/titanic/train.csv')
train[['Age','Pclass']] = SimpleImputer(strategy='mean').fit_transform(train[['Age','Pclass']])
train[['Age','Pclass']].isnull().sum()

Age       0
Pclass    0
dtype: int64

In [13]:
# 범주형 데이터 결측 처리
train=pd.read_csv('../data/titanic/train.csv')
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [14]:
train['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [15]:
train['Embarked'].isnull().sum()

2

In [32]:
# 빈도가 가장 많은 값으로 대체
train['Embarked'].fillna('S').value_counts()

S    646
C    168
Q     77
Name: Embarked, dtype: int64

In [16]:
imputer = SimpleImputer(strategy='most_frequent')
train[['Embarked','Cabin']] = imputer.fit_transform(train[['Embarked','Cabin']])
train[['Embarked','Cabin']].isnull().sum()

Embarked    0
Cabin       0
dtype: int64

In [18]:
# 문자열 데이터를 수치형 데이터로 변환
# 모델이 학습하기 위해서는 문자열 데이터들을 수치형 데이터로 변환작업
# 성별
train['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [19]:
def gender(v):
    # 남자면 1을 여자면 0리턴
    if v == 'male':
        return 1
    elif v == 'female':
        return 0

In [21]:
gender('male')

1

In [22]:
train['Sex'].head()

0      male
1    female
2    female
3    female
4      male
Name: Sex, dtype: object

In [23]:
train['Sex'].apply(gender)

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: Sex, Length: 891, dtype: int64

In [24]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [25]:
train['Sex2'] = le.fit_transform(train['Sex'])

In [26]:
train['Sex2'].head()

0    1
1    0
2    0
3    0
4    1
Name: Sex2, dtype: int32

In [27]:
train['Sex2'].value_counts()

1    577
0    314
Name: Sex2, dtype: int64

In [28]:
le.classes_

array(['female', 'male'], dtype=object)

In [29]:
train['Embarked'].value_counts()

S    646
C    168
Q     77
Name: Embarked, dtype: int64

In [30]:
train['Embarked'] = le.fit_transform(train['Embarked'])
train['Embarked'].value_counts()

2    646
0    168
1     77
Name: Embarked, dtype: int64

In [31]:
train['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [32]:
train['Age'].value_counts()

24.00    30
22.00    27
18.00    26
19.00    25
30.00    25
         ..
55.50     1
70.50     1
66.00     1
23.50     1
0.42      1
Name: Age, Length: 88, dtype: int64

### 원핫인코딩
* 2:'S',0:'C',1:'Q'
* Q + Q = S, 2Q = S
* 독립적인 데이터를 별도의 컬럼으로 분리
* 해당값은 True, 나머지는 False

In [33]:
onehot = pd.get_dummies(train['Embarked'])
onehot.columns=['C','Q','S']
onehot

C  Q  S
0    0  0  1
1    1  0  0
2    0  0  1
3    0  0  1
4    0  0  1
..  .. .. ..
886  0  0  1
887  0  0  1
888  0  0  1
889  1  0  0
890  0  1  0

[891 rows x 3 columns]

In [50]:
train['Embarked'].head()

0    2
1    0
2    2
3    2
4    2
Name: Embarked, dtype: int32

### Standard Scaling(표준화)
* 평균을 0으로, 표준편차 1이 되도록 변환

In [34]:
from sklearn.preprocessing import StandardScaler
sscaler = StandardScaler()

In [40]:
x = np.arange(10)
x[9] = 1000
x

array([   0,    1,    2,    3,    4,    5,    6,    7,    8, 1000])

In [42]:
x.mean(), x.std()

(103.6, 298.8100399919654)

In [43]:
x.reshape(-1,1)

array([[   0],
       [   1],
       [   2],
       [   3],
       [   4],
       [   5],
       [   6],
       [   7],
       [   8],
       [1000]])

In [44]:
scaled = sscaler.fit_transform(x.reshape(-1,1))

In [46]:
round(scaled.mean(),2), scaled.std()

(0.0, 1.0)

In [47]:
scaled

array([[-0.34670856],
       [-0.34336196],
       [-0.34001535],
       [-0.33666874],
       [-0.33332213],
       [-0.32997553],
       [-0.32662892],
       [-0.32328231],
       [-0.3199357 ],
       [ 2.9998992 ]])

### Normalize (정규화)
* 컬럼들간에 다른 최소/최대값이 다른 경우(범위가 다른경우)
* 정규화를 통해 최소/최대값의 기준을 동일하게 맞춰주는 것
* 네이버 영화 평점 : 0~10
* 넷플릭스 영화 평점 : 0~5

In [48]:
movie = {
    'naver':[2,4,6,8,10],
    'netflix':[1,2,3,4,5]
}
movie = pd.DataFrame(movie)
movie

naver  netflix
0      2        1
1      4        2
2      6        3
3      8        4
4     10        5

In [49]:
from sklearn.preprocessing import MinMaxScaler

In [50]:
movie2 = MinMaxScaler().fit_transform(movie)
movie2

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [0.75, 0.75],
       [1.  , 1.  ]])