In [1]:
# 텐서플로 설치
!pip install tensorflow

  Using cached Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)


In [3]:
!pip install wrapt
!pip install monotonic
!pip install netifaces

  Created wheel for netifaces: filename=netifaces-0.10.9-cp38-cp38-win_amd64.whl size=16409 sha256=aa88f72a49f6eb84d76e8f9547e7acb87dc4688dd7feed2b265e2e7c0fbc3fb4
  Stored in directory: c:\users\gw024\appdata\local\pip\cache\wheels\9b\51\d5\d4682860392414da28ba3c5ffac0243983399b868a9cced6df
Successfully built netifaces


In [3]:
conda install wrapt

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\gw024\anaconda3

  added / updated specs:
    - wrapt


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    wrapt-1.12.1               |   py38he774522_1          49 KB
    ------------------------------------------------------------
                                           Total:          49 KB

The following NEW packages will be INSTALLED:

  wrapt              pkgs/main/win-64::wrapt-1.12.1-py38he774522_1




wrapt-1.12.1         | 49 KB     |            |   0% 
wrapt-1.12.1         | 49 KB     | ########## | 100% 
wrapt-1.12.1         | 49 KB     | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

Note: you may need to restart the kernel to use updated packages.


In [4]:
import tensorflow as tf

In [3]:
tf.__version__

'2.4.1'

In [3]:
# 텐서 생성
a = tf.constant(3)

In [4]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [5]:
# 스칼라는 0차원이므로 shape에 값이 안나옴

In [6]:
# 리스트로 생성
b = tf.constant([1,2,3])
b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [7]:
# numpy에 출력되는 값이 rank
tf.rank(b)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [8]:
print(tf.rank(b))

tf.Tensor(1, shape=(), dtype=int32)


In [9]:
# 튜플로 생성
c = tf.constant(((1,2),(3,4)))
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [11]:
# numpy array로도 생성
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
d = tf.constant(arr)
d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [12]:
d.shape

TensorShape([2, 3])

In [13]:
d.dtype

tf.int32

In [14]:
# 자료형 변환
tf.cast(d, dtype=tf.float32)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [17]:
type(d)

tensorflow.python.framework.ops.EagerTensor

In [16]:
# 텐서를 넘파이어레이로 변환해서 리턴
d.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
e = np.array(d)

In [20]:
type(e)

numpy.ndarray

In [21]:
# 텐서로 변환해주는 메서드
tf.convert_to_tensor(e)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [22]:
# 기본연산
a = tf.constant(20)
b = tf.constant(10)

In [25]:
c = tf.add(a,b)
d = tf.subtract(a,b)
e = tf.multiply(a,b)
c,d,e

(<tf.Tensor: shape=(), dtype=int32, numpy=30>,
 <tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(), dtype=int32, numpy=200>)

In [26]:
c.numpy(), d.numpy()

(30, 10)

In [27]:
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])
tf.add(a,b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9])>

In [28]:
# 브로드캐스팅
a = tf.constant([1,2,3])
b = tf.constant(3)
tf.add(a,b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6])>