### Numpy
* numeric + python = 숫자와 관련된 파이썬
* 숫자 연산작업을 편하게 해주는 도구(라이브러리)
* numpy array(배열) : 파이썬 리스트와 유사
* 리스트는 자료형을 다양하게 사용 가능, numpy array는 동일한 자료형만 가능(행, 열)
* 코드도 짧아지고, 속도도 빠름

In [1]:
import numpy as np

In [2]:
plist = [1,2,3]
# 리스트를 numpy array로 변환
arr = np.array(plist)
arr

array([1, 2, 3])

In [3]:
# ndarray : n dimension array = N차원 배열
type(arr)

numpy.ndarray

In [4]:
arr.shape

(3,)

In [5]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# shape(모양), 행,열 -> 데이터의 갯수, 컬럼의 갯수
arr2.shape

(2, 3)

In [7]:
# 총 갯수
arr2.size

6

### numpy array를 만드는 방법

In [8]:
# 파이썬 리스트를 이용해서 생성
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [10]:
# 동일한값으로 생성
arr1 = np.full(6,7) # 자리수는 6개, 값은 7로 채움
arr1

array([7, 7, 7, 7, 7, 7])

In [11]:
# 모든값을 0으로 생성
arr1 = np.full(6,0)
arr1

array([0, 0, 0, 0, 0, 0])

In [15]:
arr2 = np.zeros(6,dtype=int)
arr2

array([0, 0, 0, 0, 0, 0])

In [18]:
# 모든값을 1로 생성
arr1 = np.ones(6, dtype=int)
arr1

array([1, 1, 1, 1, 1, 1])

In [19]:
# 랜덤값으로 생성
arr1 = np.random.random(10) # np모듈안에 random 모듈안에 random()함수
arr1

array([0.3134538 , 0.53266581, 0.89611681, 0.3504336 , 0.73526705,
       0.80634047, 0.64177682, 0.63369019, 0.11065875, 0.72990898])

In [31]:
# 정수랜덤값으로 생성
arr1 = np.random.randint(1,7,(2,3)) # 1~6까지의 랜덤 수, 2x3
arr1

array([[6, 4, 2],
       [4, 6, 1]])

In [32]:
# 연속된값으로 생성
arr1 = np.arange(10) # 0부터 10전까지
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# 연속된값으로 시작값과 끝값(미포함)
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
# 연속된값으로 시작값과 끝값, 스텝
arr1 = np.arange(1,11,2)
arr1

array([1, 3, 5, 7, 9])

In [36]:
'''
1부터 100까지의 값을 갖는 array를 생성하고 출력
1부터 100까지의 값 중 3의 배수만 array를 생성하고 출력
'''
arr1 = np.arange(1,101)
print(arr1)
arr2 = np.arange(3,101,3)
print(arr2)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


### 인덱싱/슬라이싱

In [37]:
arr1 = np.arange(1,20,3)
arr1

array([ 1,  4,  7, 10, 13, 16, 19])

In [43]:
# 인덱스값을 사용
print(arr1[0])
print(arr1[1])
print(arr1[6])
print(arr1[-1])
print(arr1[len(arr1)-1])

1
4
19
19
19


In [48]:
# 범위
print(arr1[0:3])
print(arr1[:3])
print(arr1[:])
print(arr1[::2])
print(arr1[::-1])

[1 4 7]
[1 4 7]
[ 1  4  7 10 13 16 19]
[ 1  7 13 19]
[19 16 13 10  7  4  1]


In [52]:
# *인덱스번호가 들어갈 하나의 자리에 2개 이상의 값이 들어가면 리스트로 묶어서 넣자
arr1[[2,4]] 

array([ 7, 13])

In [53]:
np.array([arr1[2], arr1[4]])

array([ 7, 13])

### 연산

In [54]:
arr1 = np.arange(10)
arr2 = np.arange(10,20)

In [55]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr1 + 1 # 각각의 값에 +1 *** 브로드캐스팅 broadcast

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr1 + np.array([1,1,1,1,1,1,1,1,1,1])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr1 + arr2 # 요소의 갯수가 동일해야함

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [60]:
arr1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [61]:
'''
dollar = [5000,4000,4500,5500,6000]
환율이 1달라당 1200원
won 변수에 원화로 환산한 값을 구하시오.
'''
dollar = [5000,4000,4500,5500,6000]
dollar_arr = np.array(dollar)
won = dollar_arr * 1200
won

array([6000000, 4800000, 5400000, 6600000, 7200000])

In [63]:
# *** bool 연산
arr1 = np.arange(1,20,2)
arr1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [64]:
# 각각의 값이 7보다 크면 True, 그렇지 않으면 False
arr1 > 7

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [65]:
arr1 % 3 == 0

array([False,  True, False, False,  True, False, False,  True, False,
       False])

In [66]:
# 3의 배수만 출력
# 조건에 해당(True)하는 인덱스 출력
np.where(arr1 % 3 == 0)

(array([1, 4, 7], dtype=int64),)

In [67]:
# 해당 조건에 만족하는 인덱스를 변수에 저장
w = np.where(arr1 % 3 == 0)
arr1[w]

array([ 3,  9, 15])

In [68]:
arr1[[1,4,7]]

array([ 3,  9, 15])

In [69]:
arr1[np.where(arr1 % 3 == 0)] # 데이터를 필터링

array([ 3,  9, 15])

### numpy array VS python list
* numpy array를 사용하는 이유
    * 문법 차이
    * 연산 (같은 인덱스끼리)
    * 연산 (브로드캐스팅)
    * 성능차이 (실행속도)
        * 속도차이 이유
            - 리스트는 다양한 자료형, 넘파이어레이는 하나의 자료형만 가능
            - C로 만들어진 라이브러리

In [70]:
import time
start=time.time()
plist = []
for i in range(100000000):
    plist.append(i*1200)
print(time.time()-start)

20.173150539398193


In [71]:
start=time.time()
arr = np.arange(100000000)
arr*1200
time.time()-start

0.4667503833770752

### numpy 함수

In [72]:
arr1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [73]:
# 최대값
arr1.max()

19

In [74]:
# 최소값
arr1.min()

1

In [75]:
# 평균
arr1.mean()

10.0

In [76]:
# 중앙값
np.median(arr1)

10.0

In [77]:
arr2 = np.array([1,10,99])
arr2.mean()

36.666666666666664

In [78]:
np.median(arr2)

10.0

In [79]:
# 분산
# 평균을 뺀 값(평균과의 차이)을 제곱한 합계의 평균
arr1.var()

33.0

In [80]:
# 표준편차
# 분산의 제곱근
# 표준편차가 크면 데이터들이 들죽날죽, 작으면 밋밋
arr1.std()

5.744562646538029

In [81]:
slist = ['a','b','c']
np.array(slist)

array(['a', 'b', 'c'], dtype='<U1')

In [82]:
np.array([[1,2,3],['a','b','c']])

array([['1', '2', '3'],
       ['a', 'b', 'c']], dtype='<U11')

In [85]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])